apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-secret
type: Opaque
data:
  mysql-user: {{ .Values.secret.mysqlUser | b64enc | quote }}
  mysql-password: {{ .Values.secret.mysqlPassword | b64enc | quote }}
